status = [
  "ci/circleci: contract-tests",
  "ci/circleci: docker-image-build-pr",
  "ci/circleci: docs-build",
  "ci/circleci: lint",
  "ci/circleci: python-tests",
]
# Avoid including verbose details from PR bodies
cut_body_after = "\n---\n"
block_labels = ["bors-dont-merge"]
delete_merged_branches = true
