status = [
  "ci/circleci: build_test_publish",
]
# Avoid including verbose details from PyUp in commit messages
cut_body_after = "<details>"
block_labels = ["bors-dont-merge"]
required_approvals = 1
delete_merged_branches = true 
