version: "3"

services:
  db:
    image: postgres:9.4
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    image: normandy:web
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DJANGO_CONFIGURATION=ProductionInsecure
      - DATABASE_URL=postgres://postgres@db/postgres
      - ARTIFACTS_PATH=/artifacts
    volumes:
      - test-artifacts:/artifacts
    command: first-start

  artifact-collector:
    image: ubuntu:18.04 # TODO this could be a more minimal image
    volumes:
      - test-artifacts:/artifacts
    command: |
      bash -c "
        chmod -R 777 /artifacts
        echo Waiting for artifacts
        sleep 1h  # Wait a long time
      "

volumes:
  ? test-artifacts
